# Generated by Django 3.1 on 2020-10-27 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(blank=True, max_length=48)),
                ('firstName', models.CharField(blank=True, max_length=48)),
                ('bio', models.TextField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ManyToManyField(related_name='favorited_by', to='posts.Post')),
                ('follows', models.ManyToManyField(related_name='followed_by', to='profiles.Profile')),
            ],
        ),
    ]
